### ISSUE TITLE
How to enable multiple processors?

### ISSUE THREAD

**Issue by yxinli92** [UG4/ugcore#15]
I am new to ug4 and I am running a ug4 script. It is coded for multiple processes, distributed matrices and vectors, but when I run it, it only uses a single processor. I think there should be a quick configuration to enable multiple processes? Thanks a lot!

![image](https://user-images.githubusercontent.com/38927634/45935773-c5ca0080-bf7c-11e8-94ee-5f08397eef90.png)

**Comment by yxinli92** [comment]
The script is located in your plugin repository apps/calciumDynamics_app/wave/wave_creation_noLimex.lua

**Comment by sreiter** [comment]
Hello,

please have a look at 
http://ug4.github.io/docs/page_u_g4_parallel_usage.html for information 
on how to run parallel jobs. Please make sure that ug was compiled with 
the cmake flag -DPARALLEL=ON (check it, e.g., by executing 'cmake .' in 
your build directory). This requires an installation of MPI (e.g. 
OpenMPI) on your computer.

Kind regards,
Sebastian



Am 24.09.2018 um 04:10 schrieb yxinli92:

**Comment by yxinli92** [comment]
Many thanks, Sebastian. Yes my cmake command was not including the DPARALLEL flag. I happen to notice in my cmake command there is a `-DCPU="1"` config, do you know what is that for? Compile ug4 for a particular number of processes? Do I need to change it to `-DCPU="4"` for example (my computer has 4 cores)?

Thanks again!

**Comment by sreiter** [comment]
The CPU flag is not related to parallelization. The name is a bit 
misleading, unfortunately (it determines the available block sizes for 
the matrix class). Normally -DCPU=1 is fine, unless your specific 
simulation setup requires anything else. You would receive an  error 
message during execution of the simulation script in that case.

So - regarding compilation flags it is sufficient to set -DPARALLEL=ON 
for parallel compilation of UG4. The number of cores used is then 
determined by the -n parameter to mpirun or by similar parameters to the 
scheduler. This is explained in more in the resources linked in my last 
message.

Kind regards,
Sebastian



Am 24.09.2018 um 15:47 schrieb yxinli92:

**Comment by yxinli92** [comment]
Thanks again, that solves my problem!
