### ISSUE TITLE
Scripts not found in `SCRIPT_PATH`

### ISSUE THREAD

**Issue by miho** [UG4/ugcore#2]
Potential problem: 

UG Root&Script Paths seem to be inconsistent after `ugcore` refactoring:

https://github.com/UG4/ugcore/edit/master/ugbase/ug.cpp#L117 and https://github.com/UG4/ugcore/edit/master/ugbase/ug.cpp#L156 seem to be inconsistent.

**Comment by miho** [comment]
`/` -> `GetPathSeparator()`

**Comment by sreiter** [comment]
Thanks for spotting it! It's a little unfortunate that paths are specified in two different functions in ug.cpp. An optional 'bool force' parameter to 'SetRootPath' could be an alternative (defaults to 'true').
