### ISSUE TITLE
VRL binding 

### ISSUE THREAD

**Issue by stephanmg** [UG4/ugcore#21]
Travis CI issues a build error for Clang 7.0.0 on Ubuntu 16.04.6 LTS:

`bindings_vrl.cpp:447:9: error: cannot initialize return object of type 'jstring' (aka '_jstring *') with an rvalue of type 'jlong' (aka 'long')`

Compiler information
```
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-7.0.0/bin
```
and link to Travis build log:
https://travis-ci.org/UG4/ugcore/jobs/568257699

Judging from the code in line 447 in `bindings_vrl.cpp` I assume this is a bug? (Shouldn't one cast to `jstring `instead of `jlong`?)

Best wishes,
Stephan

**Comment by miho** [comment]
I think this is resolved now. Thanks for spotting the issue.
