### ISSUE TITLE
ug4 OSX build failing on Travis

### ISSUE THREAD

**Issue by stephanmg** [UG4/ugcore#27]
Wanted to bring up a potential issue, see:
`https://travis-ci.org/github/UG4/ugcore/jobs/686475623`

Apple LLVM version 9.1.0 (clang-902.0.39.2)

is this a known issue/bug with BOOST or LLVM issue?

**Comment by anaegel** [comment]
This is related to improper support, if a new version of boost is present.

**Comment by stephanmg** [comment]
So, shall this issue #27 be closed and merged into issue #28 then? Looks like #28 is thus a duplicate of #27 or vice versa.

**Comment by mlampe** [comment]
Fixed months ago.
