### ISSUE TITLE
Support for Boost > 1.58

### ISSUE THREAD

**Issue by anaegel** [UG4/ugcore#28]
There are some issues, when a recent version of boost is present.
* Flag -DINTERNAL_BOOST is ignored.
* UG4 tries to compile externals/BoostForUG4/lib/serialization anyway.

We need a clear separation here!

**Comment by stephanmg** [comment]
Is commit 076cc4d8d41c8f94877ec2850ca1dffb2eb007fa related to this issue?

**Comment by LogashenkoDL** [comment]
BoostCPP has been updated to 1.71.
