### ISSUE TITLE
Segmentation fault in adaptive refinement

### ISSUE THREAD

**Issue by stephanmg** [UG4/ugcore#35]
I'm receiving a segmentation fault when using adaptive refinement, see and review pull request #33 

Is this the appropriate fix? If so would be great to merge it into master.

**Comment by stephanmg** [comment]
@anaegel can this issue be closed?

**Comment by anaegel** [comment]
The fix looks good to me. However, right now, I cannot confirm that this works with all tests in the test suite. If everything is working for you, please feel free to close. We can still revisit later.

**Comment by stephanmg** [comment]
Okay, I will see if I've time to verify all tests work later today. If not (either case), I'll keep this issue open.

**Comment by bsumirak** [comment]
Seems to me this was the proper fix for the issue.
In any case, tests involving the code can hardly do worse than before.
