### ISSUE TITLE
Merge toolchain files for Windows and newly added init scripts for MSVC++

### ISSUE THREAD

**Issue by miho** [UG4/ugcore#4]
Currently, there are multiple files that initialize the MSVC++ toolchain (`scripts/shell` and `cmake/toolchain`). These files should be merged into one (btw. the toolchain files are outdated and need to be improved)

**Comment by sreiter** [comment]
The .bat files in cmake/toolchain seem to be suited for very special demands and setups only. I think that they should be removed. For now the setup of the environment could be performed through the utility script in scripts/shell and the specific build setup should not be included in the general cmake/toolchain directory at all.

In the long run I agree that it would be a good idea to write a cmake-toolchain file that sets up the build environment thus avoiding the use of .bat scripts entirely (if possible) or which invokes those automatically.
