### ISSUE TITLE
Some builds are failing on Travis constantly

### ISSUE THREAD

**Issue by stephanmg** [UG4/ugcore#43]
I think this has to do something with C++11 support? Looks like compiler does not support C++11 on these builds. Maybe we need to take them out of the build matrix?

```
/Users/travis/build/UG4/ugcore/travis_root/ug4/ugcore/ugbase/common/stopwatch.h:53:10: fatal error: 'chrono' file not found
#include <chrono>
```

**Comment by mlampe** [comment]
Should be fixed by now. The problem was that VRL builds injected `-mmacosx-version-min=10.8`, which seems to imply `-stdlib=libstdc++`.

**Comment by stephanmg** [comment]
Thanks!
