### ISSUE TITLE
CI GitHub integration

### ISSUE THREAD

**Issue by miho** [UG4/ugcore#6]
Currently, we do not connect our CI infrastructure with GitHub. We should definitely do that in order to fully benefit from GitHub issues, pull request notification etc.

**Comment by miho** [comment]
Travis CI is connected and should build ugcore automatically from now on. Other possibilities are the use are the [GitHub Command Status API](https://github.com/blog/1227-commit-status-api) or the [GitHub Plugin for Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin).

**Comment by sreiter** [comment]
This looks very nice!

**Comment by miho** [comment]
Reverting parallel build because of travis-ci/apt-package-whitelist#406. Maybe we should switch to a full VM build if the issue doesn't get fixed soon.

**Comment by miho** [comment]
Travis integration needs more work (does currently only work for main branch)

**Comment by stephanmg** [comment]
Add OSX to Travis and Windows...

See closed issue #9 why to do so.

**Comment by stephanmg** [comment]
*ugcore* build times out, suggestion: use clang instead of gcc in .travis.yml.

**Comment by marscher** [comment]
Or create a build matrix for the DIM cmake parameter, I assume building each dimension would divide build time by three?

**Comment by miho** [comment]
CI integration finally works: 
- we replace ugcore that's been checked out via `ughub` with the correct commit
- ugcore builds on Travis and AppVeyor using caches. RAM usage can still be problematic. But for the current build matrix it seems to work fine.
